IT1901Website/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('bookingansvarlig.urls')),
    url(r'^', include('bookingsjef.urls')),
    url(r'^', include('band_booking.urls')),
    url(r'^', include('tekniker.urls')),
    url(r'^', include('arrangør.urls')),
    url(r'^', include('manager.urls')),
    url(r'^', include('bandmedlem.urls'))
]

manager/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import permission_required
from . import views

app_name = "manager"

urlpatterns = [
    url(r'^technical_needs/$', views.changeTechnicalneed, name='changeNeeds'),
    url(r'^technical/requirements/$', permission_required('band_booking.see_technical_requirements', login_url="/login")(views.technical_requirements), name='technical_requirements'),
    url(r'^technical/requirements/update/$', permission_required('band_booking.see_technical_requirements', login_url="/login")(views.update_technical_requirements), name='technical_requirements_update'),
]

manager/views.py
from django.shortcuts import render, redirect, reverse
from band_booking.models import Technical_needs, Band
from band_booking.forms import ChangeTechnicalneedsForm


def changeTechnicalneed(request):
    """
    Renders page for changing technical needs of the manager's band.
    """
    if request.method == 'POST':
        form = ChangeTechnicalneedsForm(request.POST)
        if form.is_valid():
            technical_need = form.save(commit=False)
            try:
                band = Band.objects.filter(manager=request.user)[:1].get()
                technical_need.band = band
            except Band.DoesNotExist:
                return redirect(reverse('band_booking:index'))
            # hvis dette fungerer går jeg tilbake til listen over behov.. Kanskje
            # return HttpResponseRedirect(reverse('changeNeeds'))
            technical_need.save()
            return redirect(reverse('manager:technical_requirements'))

    else:
        form = ChangeTechnicalneedsForm()

    context = {'form': form}

    return render(request, 'manager/technicalneeds.html', context=context)


def technical_requirements(request):
    """
    Renders page with technical requirements information for the user's band.
    """
    try:
        band = Band.objects.get(manager=request.user)
    except Band.DoesNotExist:
        return render(request, 'band_booking/error.html', {'error': "Du er ikke tilknyttet et band som manager."})
    equipment = Technical_needs.objects.filter(band=band)
    equipment_information = []
    for current_equipment in equipment:
        equipment_information.append({
            'pk': current_equipment.pk,
            'name': current_equipment.equipment_name,
            'number': current_equipment.amount,
        })
    return render(request, 'manager/equipment_collection.html', {'equipmentCollection': equipment_information,
                                                                 'band': band})


def update_technical_requirements(request):
    """
    Deletes technical requirement based on request data.
    Renders page with updated list of requirements for the manager's (user's) band
    """
    equipment_number = request.POST.getlist('equipment_number')
    equipment_pk = request.POST.getlist('pk')
    equipment_name = request.POST.getlist('equipment_name')
    delete = request.POST.getlist('delete')
    for index in range(len(equipment_number)):
        try:
            equipment = Technical_needs.objects.get(pk=equipment_pk[index])
            if equipment.band.manager != request.user:
                continue
            if delete[index] == '1':
                equipment.delete()
                continue
            if int(equipment_number[index]) < 1 or len(equipment_name[index]) < 1:
                continue
            equipment.equipment_name = equipment_name[index]
            equipment.amount = int(equipment_number[index])
            equipment.save()
        except Technical_needs.DoesNotExist:
            continue
    return redirect('manager:technical_requirements')

manager/templates/manager/equipment_collection.html
{% extends 'band_booking/base.html' %}
{% load static %}
{% block content %}
	<title>Tekniske behov</title>
	<script src="{% static 'manager/scripts/delete_on_click.js' %}"></script>
	<div class="technical-equipment-wrapper center-horizontal">
        <h1 class="technical-equipment-title">
            Utstyr for {{ band.band_name }}
        </h1>
		{% if equipmentCollection %}
			<form method="POST" action="/technical/requirements/update/">
			{% csrf_token %}
			{% for equipment in equipmentCollection %}
				<div class="technical-equipment-row"><input type="number" value="{{ equipment.pk }}" hidden name="pk"><input type="text" value="{{ equipment.name }}" name="equipment_name"><input type="number" min="1" value="{{ equipment.number }}" name="equipment_number"><input type="number" value="0" hidden name="delete"/><div class="equipment-add-delete-button basic-button hover-pointer"> Slett utstyr </div>
				</div>
			{% endfor %}
			<input type="submit" value="Lagre endringer" class="basic-button technical-equipment-save">
			</form>
		{% else %}
			<p>Det finnes ikke noen krav til utstyr i databasen</p>
		{% endif %}
        <a href="{% url 'manager:changeNeeds' %}" class="black-link"> <div class="basic-button inline-block technical-equipment-add">Legg til utstyr</div> </a>
	</div>
{% endblock %}

manager/templates/manager/technicalneeds.html
{% extends 'band_booking/base.html' %}
{% load static %}
{% block content %}
    <title> Tekniske behov </title>
    <h1 class="page-title"> Legg til utstyrsbehov </h1>
    <div class="center-horizontal">
      <form method="POST">
        {% csrf_token %}
        <!-- {{ form }} -->
        <div>
          <label for={{ form.equipment_name.id_for_label }}> Utstyr:</label>
          {{ form.equipment_name }}
        </div>
        <div>
          <label for={{ form.amount.id_for_label }}> Antall:</label>
          {{ form.amount }}
        </div>
        <input class="booking-offer-button booking-offer-save-button basic-button" type="submit" value="Lagre"/>
      </form>
    </div>
{% endblock %}