IT1901Website/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('bookingansvarlig.urls')),
    url(r'^', include('bookingsjef.urls')),
    url(r'^', include('band_booking.urls')),
    url(r'^', include('tekniker.urls')),
    url(r'^', include('arrangør.urls')),
    url(r'^', include('manager.urls')),
    url(r'^', include('bandmedlem.urls'))
]

bookingansvarlig/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import permission_required

from . import views


app_name = "bookingansvarlig"
urlpatterns = [
    url(r'^concerts/$', views.concert, name='concerts'),
    url(r'^booking/offer/(?P<offer_id>([0-9]+))/$', views.create_booking_offer, name='create_booking_offer'),
    url(r'^booking/offer/$', views.create_booking_offer, name='create_booking_offer'),
    url(r'^booking/offer/save/(?P<offer_id>([0-9]+))/$', views.update_booking_offer, name='update_booking_offer'),
    url(r'^booking/offer/save/$', views.update_booking_offer, name='update_booking_offer'),
    url(r'^bookings$', views.BookingListView.as_view(), name='bookings'),
    url(r'^bookings/filtered$', views.BookingFilteredListView.as_view(), name='bookings-filtered'),
    url(r'^booking/create_offer$', views.create_booking_offer, name='create_booking_offer'),
    url(r'^artist/$', views.search_for_artist, name='search_for_artist'),
]

bookingsjef/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import permission_required
from . import views


app_name = "bookingsjef"
urlpatterns = [
    url(r'^economy/concert/(?P<concert_id>([0-9]+))/$',permission_required('band_booking.view_concert_economic_results', login_url='/login')(views.economic_result_concert), name="economic_result"),
    url(r'^booking/offer/approve/(?P<offer_id>([0-9]+))/$', permission_required('band_booking.can_approve_booking_offers', login_url='/login')(views.approve_booking_offer), {'approved': True}, name="approve_booking_offer"),
    url(r'^booking/offer/decline/(?P<offer_id>([0-9]+))/$', permission_required('band_booking.can_approve_booking_offers', login_url='/login')(views.approve_booking_offer), {'approved': False}, name="decline_booking_offer"),
    url(r'^booking/information/$', permission_required('band_booking.can_view_term_booking_information', login_url='/login')(views.booking_information_term), name='booking_information_term'),
    url(r'^booking/calendar/(?P<scene>((storsalen|edgar|klubben|knaus)))/(?P<year>([0-9]{4}))/(?P<month>(([1][0-2]|[1-9]{1})))/$', permission_required('band_booking.can_view_term_booking_information', login_url='/login')(views.calendar), name='calendar'),
    url(r'^economy/concert/(?P<concert_id>([0-9]+))/$',permission_required('band_booking.view_concert_economic_results', login_url='/login')(views.economic_result_concert), name="economic_result"),
    url(r'^price_generator/$', permission_required('band_booking.view_concert_economic_results', login_url='/login')(views.price_generator), name="price_generator"),
    url(r'^price_input/$', permission_required('band_booking.view_concert_economic_results', login_url='/login')(views.generator_input), name="generator_input"),
    url(r'^booking/create/$', permission_required('band_booking.can_create_booking', login_url='/login')(views.create_concert), name='create_concert'),
    url(r'^booking/create/(?P<scene>((storsalen|edgar|klubben|knaus)))/(?P<date>([0-9]{2}/[0-9]{2}/[0-9]{4}))/$', permission_required('band_booking.can_create_booking', login_url='/login')(views.create_concert), name='create_concert'),
    url(r'^booking/create/band/$', permission_required('band_booking.can_create_booking', login_url='/login')(views.create_band), name='create_band'),
]

manager/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import permission_required
from . import views

app_name = "manager"

urlpatterns = [
    url(r'^technical_needs/$', views.changeTechnicalneed, name='changeNeeds'),
    url(r'^technical/requirements/$', permission_required('band_booking.see_technical_requirements', login_url="/login")(views.technical_requirements), name='technical_requirements'),
    url(r'^technical/requirements/update/$', permission_required('band_booking.see_technical_requirements', login_url="/login")(views.update_technical_requirements), name='technical_requirements_update'),
]

bookingansvarlig/views.py
from django.views import generic
from band_booking.models import Scene, Concert, Booking
from django.shortcuts import render, redirect, reverse
from django.utils import timezone
from django.core import validators
from django.core.exceptions import ValidationError, ObjectDoesNotExist
import re


def get_queries(request_method, queries, default=None):
    return [request_method.get(query, default) for query in queries]


def concert(request):
    def build_concert(concert):
        """
        :param concert: The concert object to build information about
        :return: A dictionary of information about the given concert
        """
        return {
            'pk': concert.pk,
            'name': concert.concert_title,
            'bands': [band.band_name for band in concert.bands.all()],
            'date': concert.date.strftime("%d.%m.%Y"),
            'ticket_price': concert.ticket_price,
            'genre': list(set([band.genre for band in concert.bands.all()])),
            'attendance': concert.attendance,
            'scene': concert.scene.scene_name,
        }

    def get_genres():
        """
        Finds a list of all the genre for concerts on Samfundet
        :return: All genres to be played on Samfundet
        """
        genres = []
        for concert in Concert.objects.all():
            genres += [band.genre for band in concert.bands.all()]
        return sorted(list(set(genres)))

    concerts = Concert.objects.all()

    # Collects the required query restrictions if they exist
    band_name_query, genre_query, scene_query = get_queries(request.GET, ['band_name', 'genre', 'scene'], '')

    # Finds all concerts that fulfill the search parameters
    filtered_concerts = []
    for concert in concerts.filter(scene__scene_name__icontains=scene_query, date__lte=timezone.now()).order_by('-date'):
        # Check if a band with the given band name exists in the query
        queryset_list_name = concert.bands.filter(band_name__icontains=band_name_query)
        if not queryset_list_name and band_name_query != "":
            continue

        # Check if one of the bands in the concert has the given genre
        queryset_list_genre = concert.bands.filter(genre=genre_query)
        if queryset_list_genre or genre_query == "":
            filtered_concerts.append(concert)

    # Builds the context of the view
    context = {
        'genres': get_genres(),
        'concerts': [build_concert(concert) for concert in filtered_concerts],
        'genre': genre_query,
        'scene': scene_query,
        'band_name': band_name_query,
        'scenes': [scene.scene_name for scene in Scene.objects.all()]
    }

    return render(request, 'bookingansvarlig/concert_scene.html', context)


def update_booking_offer(request, offer_id=None):
    """
    :param request: The HTTP request
    :param offer_id: The id of the offer if the offer has an id
    :return: A redirect to the edit page

    Updates the booking offer with the given ID, if no ID a new booking offer is created instead.
    Also creates a new booking offer if the user does not have permissions to edit the current booking offer
    """
    def create_new_offer(title, email, text, user, date, scene):
        """
        :param title: The title of the booking offer
        :param email: The recipient email address of the booking offer
        :param text: The booking offer text
        :param user: The user creating the offer
        :param date: The date of the offered concert
        :param scene: The scene of the offered concert
        :return: A redirect to the offer editing page
        """
        new_booking_offer = Booking(sender=user, title_name=title, recipient_email=email, email_text=text, date=date, scene=Scene.objects.get(scene_name__icontains=scene))
        new_booking_offer.save()
        request.session['saved-offer'] = True
        return redirect('bookingansvarlig:create_booking_offer', offer_id=new_booking_offer.pk)

    # Collect the POST request
    title, text, recipient_email, date, scene = get_queries(request.POST, ['title', 'message', 'email', 'date', 'scene'])
    # If one of the three fields are not set, then we return the user to the create booking offer view, as the HTML
    # requires the user to fill in all three fields.
    if title is None or text is None or recipient_email is None or date is None or scene is None:
        return redirect('bookingansvarlig:create_booking_offer')

    # Checks if the email is in a valid format, if not the user is returned
    # to the offer creation page with an error message
    try:
        validators.validate_email(recipient_email)
    except ValidationError:
        context = {'link': reverse('bookingansvarlig:update_booking_offer'),
                   'offer': {'title_name': title, 'recipient_email': recipient_email},
                   'error': "Email is not valid",
                   'email_text': text,
                   'date': date,
                   'scene': scene,
                   }
        if offer_id is not None:
            context['link'] = reverse('bookingansvarlig:update_booking_offer', kwargs={'offer_id': offer_id})
        return render(request, 'bookingansvarlig/create_booking_offer.html', context)

    # If no offer ID is given, then we create a new booking offer
    if offer_id is None:
        return create_new_offer(title, recipient_email, text, request.user, date, scene)

    try:
        # Find the booking offer
        booking_offer = Booking.objects.get(pk=offer_id)

        # If the user isn't allowed the view the booking_offer, it isn't allowed to edit it either. That is
        # a new booking offer is created instead.
        if not booking_offer.user_allowed_to_view(request.user):
            return create_new_offer(title, recipient_email, text, request.user, date, scene)

        # Update the information in the booking offer
        booking_offer.email_text = text
        booking_offer.title_name = title
        booking_offer.recipient_email = recipient_email
        booking_offer.date = date
        booking_offer.scene = Scene.objects.get(scene_name__icontains=scene)
        booking_offer.save()
        request.session['saved-offer'] = True
        return redirect('bookingansvarlig:create_booking_offer', offer_id=booking_offer.pk)

    # If no booking offer exist for the given offer ID, we create a new booking offer.
    except Booking.DoesNotExist:
        return create_new_offer(title, recipient_email, text, request.user)


def create_booking_offer(request, offer_id=None):
    """
    :param request: The HTTP request
    :param offer_id: The id of the given offer, if none a new offer is to be created
    :return: Displays information in an editable form for the current booking-offer
    """
    saved = request.session.pop('saved-offer', False)

    # If no offer ID is given, a new booking offer is to be created
    if offer_id is None:
        return render(request, 'bookingansvarlig/create_booking_offer.html',
                      {'link': reverse('bookingansvarlig:update_booking_offer'), 'scenes': [scene.scene_name for scene in Scene.objects.all()]})

    try:
        booking_offer = Booking.objects.get(pk=offer_id)
    except Booking.DoesNotExist:
        return redirect('band_booking:index')

    # Check if the user is allowed to view the booking offer, else redirect it the overview of the booking
    if not booking_offer.user_allowed_to_view(request.user):
        return redirect('band_booking:index')

    try:
        scene_name = booking_offer.scene.scene_name
    except ObjectDoesNotExist:
        scene_name = ""

    context = {'offer': booking_offer, 'saved': saved,
               'status': booking_offer.get_status_message(),
               'link': reverse('bookingansvarlig:update_booking_offer', kwargs={'offer_id': offer_id}),
               'email_text': booking_offer.email_text,
               'date': "%04d-%02d-%02d" % (booking_offer.date.year, booking_offer.date.month, booking_offer.date.day),
               'scene': scene_name,
               'scenes': [scene.scene_name for scene in Scene.objects.all()]
               }

    return render(request, 'bookingansvarlig/create_booking_offer.html', context)


class BookingListView(generic.ListView):
    """
    A view for the current bookings
    """
    template_name = 'bookingansvarlig/bookings_list.html'
    context_object_name = 'bookings'

    def get_queryset(self):
        return [booking for booking in Booking.objects.all() if booking.user_allowed_to_view(self.request.user)]


# Makes a page with just the filtered view of just the status sent
class BookingFilteredListView(generic.ListView):
    """
    A filtered view for the given bookings showing only the sent bookings
    """
    template_name = 'bookingansvarlig/bookings_list.html'
    context_object_name = 'bookings'

    def get_queryset(self):
        """
        :return: A list of all sent booking offers
        """
        return [booking for booking in Booking.objects.filter(status="S") if booking.user_allowed_to_view(self.request.user)]


def search_for_artist(request):
    """
    :param request: The HTTP request
    :return: A render of the search page for artists or if a valid name is set in the GET request a redirect to the artist information load page
    """
    artist_name = request.GET.get('name', None)
    # Check if the name is set
    if artist_name is None or artist_name == "":
        return render(request, 'bookingansvarlig/search_artist.html', {})
    # Check if the name is valid, in that case redirect
    if re.match("^[A-Za-z0-9 ]+$", artist_name):
        return redirect('band_booking:artist_load', name=artist_name)
    # Invalid name, show an error
    return render(request, 'bookingansvarlig/search_artist.html', {'name': artist_name, 'error': 'Artist navnet inneholder karakterer som ikke er støttet. Støttede karakterer er mellomrom, bokstavene fra A til Z og tall'})

bookingansvarlig/templates/bookingansvarlig/bookings_list.html
{% extends 'band_booking/base.html' %}
{% block content %}
    {% url 'bookingansvarlig:bookings-filtered' as filtered_url %}
    <title>Bookingtilbud</title>
    <div class="booking-list-wrapper center-horizontal">
        <div class="booking-overview-button-container booking-overview-float-down">
            <a href="{% url 'bookingansvarlig:create_booking_offer' %}" class="booking-offer-button button black-link">
                <div class="basic-button booking-list-new-offer-button">
                    Nytt bookingtilbud
                </div>
            </a>
        </div>

        <div class="booking-overview-button-container">
            <a href="{% url 'bookingansvarlig:bookings-filtered' %}" class="booking-offer-button button black-link">
                <div class="basic-button booking-list-filter-button{% if request.get_full_path == filtered_url %} disabled-filter-button{% endif %}">
                    Sendt
                </div>
            </a>
        </div>

        <div class="booking-overview-button-container">
            <a href="{% url 'bookingansvarlig:bookings' %}" class="booking-offer-button button black-link">
                <div class="basic-button booking-list-filter-button{% if request.get_full_path != filtered_url %} disabled-filter-button{% endif %}">
                    Alle
                </div>
            </a>
        </div>


        <table class="booking-overview-table">
            <thead class="booking-overview-table-header">
            <tr>
                <th>Tittel</th>
                <th>Mottaker</th>
                <th>Ansvarlig</th>
                <th>Tilbud</th>
                <th>Dato</th>
                <th>Status</th>
                {% if perms.band_booking.can_approve_booking_offers %}
                    <th>Godkjenn</th>
                {% endif %}
            </tr>
            </thead>
            <tbody>
            {% for booking in bookings %}
                <tr>
                    <td>{{ booking.title_name }}</td>
                    <td>{{ booking.recipient_email }}</td>
                    {% if booking.sender.first_name %}
                        <td>{{ booking.sender.first_name }} {{ booking.sender.last_name }}</td>
                    {% else %}
                        <td>{{ booking.sender.username }}</td>
                    {% endif %}
                    <td><a href="{% url 'bookingansvarlig:create_booking_offer' booking.pk %}">Se tilbud</a></td>
                    <td>{{ booking.date }}</td>
                    <td class="{{ booking.status }}">{{ booking.get_status_word }}</td>
                    {% if perms.band_booking.can_approve_booking_offers %}
                        {% if booking.status == "U" %}
                            <td class=" booking-offer-accept-buttons booking-offer-disabled-approval-buttons">
                                <a href="{% url 'bookingsjef:approve_booking_offer' booking.pk %}" class="black-link">
                                    <div class="booking-offer-accept-button S">
                                        Godkjenn
                                    </div>
                                </a>
                                <a href="{% url 'bookingsjef:decline_booking_offer' booking.pk %}" class="black-link">
                                    <div class="booking-offer-decline-button N">
                                        Avslå
                                    </div>
                                </a>
                            </td>
                        {% else %}
                            <td class="booking-offer-disabled-approval-buttons">

                            </td>
                        {% endif %}
                    {% endif %}

                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

bookingansvarlig/templates/bookingansvarlig/concert_scene.html
{% extends 'band_booking/base.html' %}
{% load static %}
{% block content %}
    <script src="{% static 'bookingansvarlig/scripts/concert_dropdown_selector.js' %}"></script>
    <title>Konserter</title>

    <div class="center-horizontal concert-overview-wrapper">
        <h1 class="concert-overview-title">Konserter</h1>
        <div class="concert-overview-filter-bar">
            <div class="table-row">
                <div class="table-cell">
                    <h4>Søk etter band</h4>

                    <!-- This adds a search bar to the view where the user can search for bands-->
                    <form method="GET" action="" id="concert_filters">
                        <input type="hidden" name="scene" id="scene_selector" value="{{ scene }}" hidden/>
                        <input type="hidden" name="genre" id="genre_selector" value="{{ genre }}" hidden/>
                        <input type="text" class="concert-overview-search-bar" name="band_name" placeholder="Skriv inn navn på band"
                               value="{{ band_name }}"/>
                        <input type="submit" value="Søk"/>
                    </form>
                </div>

                <div class="table-cell">
                    <div class="dropdown">
                        Scene: <span class="dropdown-currently-selected">{% if scene == "" %}Ingen
                        valgt{% endif %}{{ scene }}</span>
                        <div class="dropdown-wrapper">
                            {% for current_scene in scenes %}
                                <div class="dropdown-item scene-item{% if current_scene == scene %} dropdown-currently-selected-item{% endif %}">{{ current_scene }}</div>
                            {% endfor %}
                        </div>
                    </div>
                </div>

                <div class="table-cell">
                    <div class="dropdown">
                        Sjanger: <span class="dropdown-currently-selected">{% if genre == "" %}Ingen
                        valgt{% endif %}{{ genre }}</span>
                        <div class="dropdown-wrapper">
                            {% for current_genre in genres %}
                                <div class="dropdown-item genre-item{% if current_genre == genre %} dropdown-currently-selected-item{% endif %}">{{ current_genre }}</div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="concert-overview-information-table table">
            <div class="table-head concert-overview-table-head">
                <div class="table-cell">
                    Scene
                </div>
                <div class="table-cell">
                    Konsert navn
                </div>
                <div class="table-cell">
                    Band
                </div>
                <div class="table-cell">
                    Dato
                </div>
                <div class="table-cell">
                    Billettpris
                </div>
                <div class="table-cell">
                    Sjanger
                </div>
                <div class="table-cell">
                    Publikumstall
                </div>
                {% if perms.band_booking.view_concert_economic_results %}
                    <div class="table-cell">
                        Rapport
                    </div>
                {% endif %}
            </div>
            {% for concert in concerts %}
                <div class="table-row">
                    <div class="table-cell">
                        {{ concert.scene }}
                    </div>
                    <div class="table-cell">
                        {{ concert.name }}
                    </div>
                    <div class="table-cell">
                        {% for band in concert.bands %}
                            <span class="concert-overview-band-name">
                            <a href="/artist/{{ band }}">
                                {{ band }}
                            </a>
                        </span>
                        {% endfor %}
                    </div>
                    <div class="table-cell">
                        {{ concert.date }}
                    </div>
                    <div class="table-cell">
                        {{ concert.ticket_price }} kr
                    </div>
                    <div class="table-cell">
                        {% for genre in concert.genre %}
                            <span class="concert-overview-genre-band">{{ genre }}</span>
                        {% endfor %}
                    </div>
                    <div class="table-cell">
                        {{ concert.attendance }}
                    </div>
                    {% if perms.band_booking.view_concert_economic_results %}
                        <div class="table-cell">
                            <a href="/economy/concert/{{ concert.pk }}/">
                                Rapport
                            </a>
                        </div>
                    {% endif %}
                </div>
            {% endfor %}

        </div>
    </div>
{% endblock %}

bookingansvarlig/templates/bookingansvarlig/create_booking_offer.html
{% extends 'band_booking/base.html' %}
{% load static %}
{% block content %}
    <title> Bookingtilbud </title>
    <script src="{% static 'bookingansvarlig/scripts/concert_overview.js' %}"></script>
    <div class="create-booking-offer-wrapper center-horizontal">
        {% if saved %}
            <div class="booking-offer-saved-message booking-offer-status-message" id="saved-message">
                <span class="center-booking-status-message-vertical">
                    Tilbud er lagret
                </span>
            </div>
        {% endif %}
        {% if error %}
            <div class="error-message booking-offer-status-message" id="error-message">
                <span class="center-booking-status-message-vertical">
                    {{ error }}
                </span>
            </div>
        {% endif %}
        {% if offer %}
            <div class="{{ offer.status }} booking-offer-status-message" id="offer-status-message">
                <span class="center-booking-status-message-vertical">
                    {{ status }}
                </span>
            </div>
        {% endif %}
		<form class="booking-offer-offer-form" method="post" action="{{ link }}" onsubmit="return checkInput()" autocomplete="off">
            {% csrf_token %}
			<h1 class="page-title"> Bookingtilbud </h1>

			<div class="booking-offer-text_fields">
				<div class="booking-offer-title_field">
					<label class="booking-offer-label"  for="title" >
						Tittel:
					</label>
					<br>
					<input class="booking-offer-title-input-field" type="text" name="title" id="title" placeholder="Bookingtilbud tittel" required {% if offer %}value="{{ offer.title_name }}"{% endif %}>
				</div>

				<div class="booking-offer-email">
					<label class="booking-offer-label"  for="email">
						E-post manager:
					</label>
					<br>
					<input class="booking-offer-email-input-field" type="email" name="email" id="email" placeholder="Managers epost" required {% if offer %}value="{{ offer.recipient_email }}"{% endif %}>
				</div>
			</div>
            <input type="hidden" name="scene" id="scene_selector" value="{{ scene }}" hidden required/>
			<br>


            <div class="booking-offer-date">
                <label for="date_selector">Dato: &nbsp;</label>
                <input id="date_selector" name="date" type="date" placeholder="yyyy-mm-dd" {% if offer %}value="{{ date }}"{% endif %} required>
            </div>

            <div class="table-cell booking-offer-scene-selector">
                <div class="dropdown">
                    Scene: <span id="currently-selected-scene" class="dropdown-currently-selected">{% if not scene %}Ingen
                    valgt{% endif %}{{ scene }}</span>
                    <div class="dropdown-wrapper">
                        {% for current_scene in scenes %}
                            <div class="dropdown-item scene-item{% if current_scene == scene %} dropdown-currently-selected-item{% endif %}">{{ current_scene }}</div>
                        {% endfor %}
                    </div>
                </div>
            </div>


			<div class="booking-offer-email-text">
				<label class="booking-offer-label" for="message">Beskjed: </label>
				<br>
				<textarea class="booking-offer-message-field" id="message" name="message" placeholder="Bookingtilbud tekst" required>{% if offer %}{{ email_text }}{% endif %}</textarea>
				<br> <br>
			</div>

			<input class="booking-offer-button booking-offer-save-button basic-button" type="submit" value="Lagre tilbud"/>
		</form>
        <a href="{% url 'bookingansvarlig:bookings' %}">
            <button class="booking-offer-button booking-offer-menu-button basic-button"> Oversikt tilbud </button>
        </a>
    </div>
{% endblock %}

bookingansvarlig/templates/bookingansvarlig/search_artist.html
{% extends 'band_booking/base.html' %}
{% load static %}
{% block content %}
    <title>Søk på artist</title>
    <script src="{% static 'bookingansvarlig/scripts/search_artist.js' %}"></script>
    {% if error %}
        <div id="error-message" class="artist-search-error-message error-message center-horizontal">
            {{ error }}
        </div>
    {% endif %}
    <div class="centered artist-search-area">
        <form class="artist-search-form" action="" method="get">
            <label for="artist_name" class="bold">Søk på artist:</label> <br/>
            <input id="artist_name" type="text" value="{% if name %}{{ name }}{% endif %}" placeholder="Søk på artist navn" name="name" class="artist-search-box">
            <input class="artist-search-search-button basic-button" type="submit" value="Søk">
        </form>
    </div>
{% endblock %}

bookingansvarlig/templates/bookingansvarlig/tilbudView.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<link type="text/css" rel="stylesheet" href="tilbudViewStyle.css">
		<title> Bookingtilbud </title>
	</head>

	<body>
	<main>
		<form>
			<h2> Bookingtilbud </h2>
			
			<div class="text_fields">
				<div class="title_field">
					<label for="title" >
						Tittel:
					</label>
					<br>
					<input type="text" name="title" id="title">
				</div>
				
				<div class="email">
					<label for="email"> 
						E-post mottaker: 
					</label>
					<br>
					<input type="text" name="e-post" id="email">
				</div>
			</div>
			
			<br>

			<div class="email_text">
				Beskjed: 
				<br>
				<textarea name="message"></textarea>
				<br> <br>
			</div>
			
			<button type="button" onclick="confirm('Du er i ferd med aa sende forespoersel om tilbud. Er du sikker paa at du vil fortsette?')">Send tilbud til godkjenning</button>
		</form>
	</main>
	</body>
</html>