IT1901Website/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('bookingansvarlig.urls')),
    url(r'^', include('bookingsjef.urls')),
    url(r'^', include('band_booking.urls')),
    url(r'^', include('tekniker.urls')),
    url(r'^', include('arrangør.urls')),
    url(r'^', include('manager.urls')),
    url(r'^', include('bandmedlem.urls'))
]

bookingsjef/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import permission_required
from . import views


app_name = "bookingsjef"
urlpatterns = [
    url(r'^economy/concert/(?P<concert_id>([0-9]+))/$',permission_required('band_booking.view_concert_economic_results', login_url='/login')(views.economic_result_concert), name="economic_result"),
    url(r'^booking/offer/approve/(?P<offer_id>([0-9]+))/$', permission_required('band_booking.can_approve_booking_offers', login_url='/login')(views.approve_booking_offer), {'approved': True}, name="approve_booking_offer"),
    url(r'^booking/offer/decline/(?P<offer_id>([0-9]+))/$', permission_required('band_booking.can_approve_booking_offers', login_url='/login')(views.approve_booking_offer), {'approved': False}, name="decline_booking_offer"),
    url(r'^booking/information/$', permission_required('band_booking.can_view_term_booking_information', login_url='/login')(views.booking_information_term), name='booking_information_term'),
    url(r'^booking/calendar/(?P<scene>((storsalen|edgar|klubben|knaus)))/(?P<year>([0-9]{4}))/(?P<month>(([1][0-2]|[1-9]{1})))/$', permission_required('band_booking.can_view_term_booking_information', login_url='/login')(views.calendar), name='calendar'),
    url(r'^economy/concert/(?P<concert_id>([0-9]+))/$',permission_required('band_booking.view_concert_economic_results', login_url='/login')(views.economic_result_concert), name="economic_result"),
    url(r'^price_generator/$', permission_required('band_booking.view_concert_economic_results', login_url='/login')(views.price_generator), name="price_generator"),
    url(r'^price_input/$', permission_required('band_booking.view_concert_economic_results', login_url='/login')(views.generator_input), name="generator_input"),
    url(r'^booking/create/$', permission_required('band_booking.can_create_booking', login_url='/login')(views.create_concert), name='create_concert'),
    url(r'^booking/create/(?P<scene>((storsalen|edgar|klubben|knaus)))/(?P<date>([0-9]{2}/[0-9]{2}/[0-9]{4}))/$', permission_required('band_booking.can_create_booking', login_url='/login')(views.create_concert), name='create_concert'),
    url(r'^booking/create/band/$', permission_required('band_booking.can_create_booking', login_url='/login')(views.create_band), name='create_band'),
]

manager/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import permission_required
from . import views

app_name = "manager"

urlpatterns = [
    url(r'^technical_needs/$', views.changeTechnicalneed, name='changeNeeds'),
    url(r'^technical/requirements/$', permission_required('band_booking.see_technical_requirements', login_url="/login")(views.technical_requirements), name='technical_requirements'),
    url(r'^technical/requirements/update/$', permission_required('band_booking.see_technical_requirements', login_url="/login")(views.update_technical_requirements), name='technical_requirements_update'),
]

band_booking/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.utils import timezone


# Create your models here.

class Scene(models.Model):
    """
    Class representing scene.
    """
    number_of_seats = models.IntegerField()
    handicap_accessible = models.NullBooleanField()
    related_name = 'a_scene'
    expenditure = models.IntegerField(default=0)

    # All the choices for the scenes
    STORSALEN = 'Storsalen'
    KLUBBEN = 'Klubben'
    KNAUS = 'Knaus'
    EDGAR = 'Edgar'

    SCENE_CHOICES = (
        (STORSALEN, 'storsalen'),
        (KLUBBEN, 'klubben'),
        (KNAUS, 'knaus'),
        (EDGAR, 'edgar')
    )
    scene_name = models.CharField(
        max_length=16,
        choices=SCENE_CHOICES,
        default=STORSALEN,
    )

    def __str__(self):
        return self.scene_name


class Band(models.Model):
    """
    Class representing band.
    """
    band_name = models.CharField(max_length=30)
    manager = models.OneToOneField(User, limit_choices_to={'groups__name': "Manager"}, null=True, blank=True)
    genre = models.CharField(max_length=20)
    band_member = models.ManyToManyField(User, limit_choices_to={'groups__name': "Bandmedlem"}, related_name='band_member', blank=True)
    booking_price = models.IntegerField(default=0)
    streaming_numbers = models.IntegerField(default=0)

    related_name = "a_band"

    def __str__(self):
        return self.band_name

    def get_band_manager_bookings(self):
        """
        :return: Returns all bookings sent to the manager of the band. Else raises an error.
        Raises:
            ValueError: if band's manager doesn't have an email
        """

        try:
            manager_email = self.manager.email
        except:
            raise ValueError("Manager's email missing")
        return Booking.objects.filter(recipient_email=manager_email)

    @classmethod
    def get_users_band(cls, user: User):
        """
        :param user: The user
        :return: The band the user is a member of if it exists
        """
        try:
            return Band.objects.filter(band_member=user)[:1].get()
        except Band.DoesNotExist:
            return None

    @classmethod
    def equipment(cls, user: User):
        """
        :param user: The user for which we want to find equipment needed
        :return: The equipment needed for the band of the user, if the user is a member of a band.
        """
        user_band = Band.objects.filter(band_member=user)[0]
        return Technical_needs.objects.filter(band=user_band)


class Concert(models.Model):
    """
    Class representation of concert.
    """
    concert_title = models.CharField(max_length=50)
    date = models.DateField()  # got en error with default=date.today() when migrating, so it's been removed
    bands = models.ManyToManyField(Band)  # There can play many bands on the concert and band can play many concerts
    scene = models.ForeignKey(Scene, null=True, blank=True)  # only one scene per concert, but many concerts per scene
    personnel = models.ManyToManyField(User, blank=True)
    attendance = models.IntegerField(default=0)
    ticket_price = models.IntegerField(default=0)
    booking_price = models.IntegerField(default=0)
    organizer = models.ForeignKey(User, limit_choices_to={'groups__name': 'Arrangør'}, null=True, blank=True, related_name='organizer')
    related_name = 'a_concert'

    GUARD_EXPENSE = 1000
    BOOKED = 'B'
    CONTACTED = 'C'
    PAID = 'P'

    STATUS_CHOICES = (
        (BOOKED, 'Booked'),
        (CONTACTED, 'Contacted'),
        (PAID, 'Paid'),
    )

    status = models.CharField(
        max_length=1,
        choices=STATUS_CHOICES,
        default=BOOKED
    )

    def __str__(self):
        return self.concert_title

    def calc_econ_result(self):
        """
        :return: The economic results for the concert
        Calculates the concert's economic result
        """
        return self.ticket_price * self.attendance - self.booking_price - self.scene.expenditure - self.GUARD_EXPENSE

    #
    @property
    def economic_result(self):
        """
        :return: The economic results for the concert
        The economic results for the concert disguised as a field.
        """
        return self.calc_econ_result()


class Technical_needs(models.Model):
    """
    Class representing specific technical needs for the band
    """
    equipment_name = models.CharField(max_length=128, default=' ')
    amount = models.IntegerField(default=1)
    band = models.ForeignKey(Band)

    def __str__(self):
        return self.equipment_name


class Booking(models.Model):
    """
    Class representing band booking.
    """

    EMAIL_MAX_LENGTH = 5000

    sender = models.ForeignKey(User, limit_choices_to={'groups__name': 'Bookingansvarlig'}, null=True, blank=True)
    title_name = models.CharField(max_length=50, default=' ')
    recipient_email = models.EmailField(max_length=50, default=' ')
    email_text = models.CharField(max_length=EMAIL_MAX_LENGTH, default='Booking offer goes here')
    date = models.DateField(default=timezone.now)
    scene = models.ForeignKey(Scene, null=True, blank=True, default=True)

    UNDECIDED = 'U'
    NOT_APPROVED = 'N'
    APPROVED = 'A'
    SENT = 'S'

    STATUS_CHOICES = (
        (UNDECIDED, 'Undecided'),
        (NOT_APPROVED, 'Not approved'),
        (APPROVED, 'Approved'),
        (SENT, 'Sent'),
    )
    status = models.CharField(
        default='U',
        max_length=1,
        choices=STATUS_CHOICES,
    )

    def get_status_message(self):
        """
        Returns a status message in Norwegian for the current status of the booking offer.
        """
        return "Tilbudet er " + self.get_status_word().lower()

    def get_status_word(self):
        """
        Returns a status word in Norwegian for the current status of the booking offer
        """
        status_words = {'U': 'Under godkjenning', 'N': 'Ikke godkjent', 'A': 'Godkjent', 'S': 'Sendt'}
        return status_words[self.status]

    def user_allowed_to_view(self, user):
        """
        Checks if the given user is allowed to view the booking offer
        """
        return self.sender == user or user.has_perm('band_booking.view_all_booking_offers')

    def __str__(self):
        return self.title_name

    def change_status(self, new_status):
        """
        :param new_status: The new status of the booking
        :return: None
        Changes the status of the booking to the new_status
        """
        if new_status in (Booking.UNDECIDED, Booking.NOT_APPROVED, Booking.APPROVED, Booking.SENT):
            self.status = new_status
            self.save()


@receiver(models.signals.post_save, sender=Booking)
def handle_change(sender, **kwargs):
    """
    :param sender: The sender of the Django signal
    :param kwargs: Keyword arguments for the give Django signal
    :return: None
    Sends an email for the given booking that had a change if the stauts was changed to approved.
    """
    booking_object = kwargs['instance']
    if booking_object.status == Booking.APPROVED:
        from bookingansvarlig.actions.send_booking import send_booking
        send_booking(booking_object)
        booking_object.change_status(Booking.SENT)

bookingsjef/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
from band_booking.models import Concert, Booking, Scene
from .actions.concert_overview_term import get_information_this_term, build_information_month
from bookingsjef.algorithms.ticket_price import get_ticket_prices_for_scenes
from django.http import HttpResponse
from band_booking.forms import CreateBandForm, CreateConcertForm
from datetime import datetime


def economic_result_concert(request, concert_id):
    """
    Renders a page with economic results of the concert
    """
    concert = get_object_or_404(Concert, pk=concert_id)
    context = {
        'title': concert.concert_title,
        'date': concert.date.strftime('%d.%m.%Y'),
        'attendance': concert.attendance,
        'bands': [band.band_name for band in concert.bands.all()],
        'economic_result': '%.2f kr' % concert.economic_result,
        'expenses': {
            'Guards': '%.2f kr' % concert.GUARD_EXPENSE,
            'Drift scene': '%.2f kr' % concert.scene.expenditure,
            'Band': '%.2f kr' % concert.booking_price,
        },
        'income': {
            'Tickets': '%.2f kr' % (concert.ticket_price * concert.attendance),
        },
    }
    return render(request, 'bookingsjef/economic_result.html', context)


def approve_booking_offer(request, offer_id, approved=False):
    """
    Changes booking status to APPROVED.
    """
    try:
        offer = Booking.objects.get(pk=offer_id)
        if offer.status not in [Booking.UNDECIDED, Booking.NOT_APPROVED]:
            return redirect('bookingansvarlig:bookings')
        if not approved:
            offer.change_status(Booking.NOT_APPROVED)
        else:
            offer.change_status(Booking.APPROVED)
        offer.save()
        return redirect('bookingansvarlig:bookings')
    except Booking.DoesNotExist:
        print('does not exist')
        return redirect('bookingansvarlig:bookings')


def calendar(request, year, month, scene):
    """
    Renders calendar page with booking overview for the month and scene based on input parameter.
    """
    return render(request, "bookingsjef/booking-overview-term.html", build_information_month(int(year), int(month), scene))


def booking_information_term(request):
    """
    Renders page with booking information for the current semester.
    """
    return render(request, "bookingsjef/booking_information_term.html", get_information_this_term())


def generator_input(request):
    """
    Renders page that allow the user to generate ticket prices for specific band and booking price.
    """
    context = {

    }
    return render(request, 'bookingsjef/generator_input.html', context)


def price_generator(request):
    """
    Generates band prices for all the scenes
    """
    bandname = request.POST.get('band', '')
    price = int(request.POST.get('price', ''))
    price_generated = get_ticket_prices_for_scenes(bandname, price)
    info = []
    try:
        for list in price_generated:
            name = list[0].scene_name
            price = list[1]

            info.append({
                'name': name,
                'price': price

            })
        context = {
            'info': info,
        }
        return render(request, 'bookingsjef/generate_price.html', context)
    except TypeError:
        return HttpResponse('Bandet eksisterer ikke i våre databaser')


def create_concert(request, date=None, scene=None):
    """
    :param request: The HTTP request
    :param date: The date
    :param scene: The scene
    :return: A redirect or render depending on the validity of the form
    """
    if request.method == 'POST':
        form = CreateConcertForm(request.POST)
        # Check if the form is valid
        if form.is_valid():
            form.save()
            return redirect(reverse('bookingsjef:booking_information_term'))
        return render(request, 'bookingsjef/create_concert.html', context={'form': form})

    # Try selecting a valid scene
    if scene:
        try:
            scene = Scene.objects.get(scene_name__icontains=scene)
        except Scene.DoesNotExist:
            scene = None

    # Create the context of the request
    context = {'form': CreateConcertForm(initial={'date': (date or datetime.now()), 'scene': scene})}
    return render(request, 'bookingsjef/create_concert.html', context=context)


def create_band(request):
    """
    :param request: The HTTP request
    :return: A redirect to an error page if there are no available managers or to the concert creation page if the form is correct.
            Else a render of the creation page
    """
    if request.method == 'POST':
        form = CreateBandForm(request.POST)
        # Check if the form is valid
        if form.is_valid():
            form.save()
            return redirect(request.POST.get('url'))

    # Create the context of the request
    context = {'form': CreateBandForm(request.POST), 'url': (request.POST.get('url') or reverse('bookingsjef:create_concert'))}

    # Check if there are any choices of managers
    if not context['form'].fields['manager'].widget.choices:
        return render(request, 'band_booking/error.html', {'error': "Ingen ledige managers i systemet. Kontakt system administratoren for å få registrert nye managers"})
    return render(request, 'bookingsjef/create_band.html', context=context)

bookingsjef/templates/bookingsjef/booking-overview-term.html
{% extends 'band_booking/base.html' %}
{% block content %}
    <div class="calendar-wrapper center-horizontal">
        <h1 class="calendar-header-center">{{ scene }}</h1>
        <div class="calendar-controls">
            {% if previous %}
                <a href="{{ previous }}" class="black-link calendar-previous-month">
                    <div >
                        &lt; Forrige måned
                    </div>
                </a>
            {% else %}
                <div class="calendar-previous-month-adjuster">

                </div>
            {% endif %}
            {% if next %}
                <a href="{{ next }}" class="black-link calendar-next-month">
                    <div >
                        Neste måned &gt;
                    </div>
                </a>
            {% endif %}
            <div class="calendar-month">
                {{ month }}
            </div>
        </div>
        <div class="calendar-fields">
            <div class="calendar-header-field">
                Mandag
            </div>
            <div class="calendar-header-field">
                Tirsdag
            </div>
            <div class="calendar-header-field">
                Onsdag
            </div>
            <div class="calendar-header-field">
                Torsdag
            </div>
            <div class="calendar-header-field">
                Fredag
            </div>
            <div class="calendar-header-field">
                Lørdag
            </div>
            <div class="calendar-header-field">
                Søndag
            </div>
            {% for i in empty_dates %}
                <div class="calendar-field-empty calendar-field">
                    &nbsp
                </div>
            {% endfor %}
            {% for date in dates %}
                <div class="calendar-field {% if date.greyed %}calendar-field-empty{% endif %} {{ date.booked }}">
                    {{ date.date }}
                    {% if date.band %}
                        <div class="calendar-date-band">
                            {{ date.band }}
                        </div>
                    {% elif date.email %}
                        <div class="calendar-date-email">
                            {{ date.email }}
                        </div>
                    {% elif not date.greyed %}
                        {% if perms.band_booking.can_create_booking %}
                            <div class="calendar-date-band">
                                <a href="{% url 'bookingsjef:create_concert' scene=scene.lower date=date.url_date %}" class="black-link">Ny booking</a>
                            </div>
                        {% endif %}
                    {% endif %}
                </div>
            {% endfor %}
            {% for i in empty_dates_end %}
                <div class="calendar-field-empty calendar-field">
                    &nbsp
                </div>
            {% endfor %}
        </div>
        <div class="calendar-color-explanation">
            <div class="calendar-color-explanation-single">
                <div class="calendar-color-box booked">

                </div>
                Booket
            </div>
            <div class="calendar-color-explanation-single">
                <div class="calendar-color-box offer-sent">
                </div>
                Tilbud sendt
            </div>
            <div class="calendar-color-explanation-single">
                <div class="calendar-color-box not-booked">
                </div>
                Ledig
            </div>
        </div>
        <div class="back-button">
            <a class="black-link" href="{% url 'bookingsjef:booking_information_term' %}">
                <div class="basic-button"> Tilbake </div>
            </a>
        </div>
    </div>
{% endblock %}

bookingsjef/templates/bookingsjef/booking_information_term.html
{% extends 'band_booking/base.html' %}
{% block content %}
    <title>Booking dette semesteret</title>
    <div class="centered booking-information-wrapper">
        <div class="booking-information-scenes">
            <div>
                <div class="booking-information-scene-title-placeholder">
                </div>
                <div class="booking-information-scene-information booking-information-scene-middle-element">
                    Antall bookete datoer:
                </div>
                <div class="booking-information-scene-information booking-information-scene-middle-element">
                    Antall ledige datoer:
                </div>
                <div class="booking-information-scene-information booking-information-scene-middle-element margin-top-medium">
                    Antall tilbud sent:
                </div>
                <div class="booking-information-scene-information">
                    Kalender for semesteret:
                </div>
            </div>
            {% for scene in scenes %}
            <div>
                <div class="booking-information-scene-title">
                    {{ scene.name }}
                </div>
                <div class="booking-information-scene-middle-element">
                    {{ scene.booked }}
                </div>
                <div class="booking-information-scene-middle-element">
                    {{ scene.unbooked }}
                </div>
                <div class="booking-information-scene-middle-element margin-top-medium">
                    {{ scene.offers }}
                </div>
                <a href="{{ scene.calendar }}" class="calendar-link">
                    <div>
                        Kalender
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

bookingsjef/templates/bookingsjef/create_band.html
{% extends 'band_booking/base.html' %}
{% block content %}
    <div class="wrapper-create-booking center-horizontal">
        <h2>Lag nytt band</h2>
        {{ form.errorlist }}
        <form action="" method="post">
            {% csrf_token %}
            <div class="booking-form-field">
                <label for="id_band_name">Band navn:</label>
                {{ form.band_name }}
            </div>
            <div class="booking-form-field">
                <label for="id_manager">Manager:</label>
                {{ form.manager }}
            </div>
            <div class="booking-form-field">
                <label for="id_genre">Sjanger:</label>
                {{ form.genre }}
            </div>
            <input type="submit" class="basic-button"/>
            <input type="text" name="url" value="{{ url }}"hidden/>
        </form>
    </div>
{% endblock %}

bookingsjef/templates/bookingsjef/create_concert.html
{% extends 'band_booking/base.html' %}
{% load static %}
{% block content %}
    <script src="{% static 'bookingsjef/scripts/new_band.js' %}"></script>
    <div class="wrapper-create-booking center-horizontal">
        <h2>
            Registrer konsert
        </h2>
        <form method="post">
            {% csrf_token %}
            <div class="booking-form-field">
                <label for="id_concert_title">Tittel:</label>
                {{ form.concert_title }}
            </div>
            <div class="booking-form-field">
                <label for="id_date">Dato (dd/mm/yyyy):</label>
                {{ form.date }}
            </div>
            <div class="booking-form-field">
                <label for="id_bands">Band:</label>
                {{ form.bands }}
                <button id="create_new_band" class="new_band hover-pointer"></button>
            </div>
            <div class="booking-form-field">
                <label for="id_scene">Scene:</label>
                {{ form.scene }}
            </div>
            <div class="booking-form-field">
                <label for="id_ticket_price">Billettpris:</label>
                {{ form.ticket_price }}
            </div>
            <div class="booking-form-field">
                <label for="id_booking_price">Booking kostnad:</label>
                {{ form.booking_price }}
            </div>
            <input type="submit" class="basic-button"/>
        </form>
    </div>

{% endblock %}

bookingsjef/templates/bookingsjef/economic_result.html
{% extends "band_booking/base.html" %}
{% load static %}
{% block content %}
    <title>{{ title }}</title>
    <div class="economic-result-wrapper center-horizontal">
        <h1 class="economic-result-title">Rapport - {{ title }} - {{ date }}</h1>
        <div class="table economic-result-information-table">
            <div class="economic-result-information-table-header">
                <div class="table-cell economic-result-information-table-title">
                    Felt
                </div>

                <div class="table-cell economic-result-information-table-title">
                    Verdi
                </div>
            </div>
            <div>
                <div class="table-cell">
                    Band:
                </div>
                <div class="table-cell">
                    <div class="table economic-result-band-table">
                    {% for band in bands %}
                        <div class="table-row">
                            <div class="table-cell-small">
                                <a href="/artist/{{ band.title }}" class="economic-result-link"> {{ band.title }} </a>
                            </div>
                        </div>
                    {% endfor %}
                    </div>
                </div>
            </div>
            <div>
                <div class="table-cell">
                    Publikumstall
                </div>
                <div class="table-cell">
                    {{ attendance }}
                </div>
            </div>
            <div>
                <div class="economic-result-information-table-title table-cell">
                    Kostnader:
                </div>
            </div>
            {% for expense, cost in expenses.items %}
                <div>
                    <div class="table-cell">
                        {{ expense }}
                    </div>
                    <div class="table-cell">
                        {{ cost }}
                    </div>
                </div>
            {% endfor %}
            <div>
                <div class="economic-result-information-table-title table-cell">
                    Inntekter:
                </div>
            </div>
            {% for item, value in income.items %}
                <div>
                    <div class="table-cell">
                        {{ item }}
                    </div>
                    <div class="table-cell">
                        {{ value }}
                    </div>
                </div>
            {% endfor %}
            <div>
                <div class="economic-result-information-table-title table-cell">
                    Økonomisk resultat
                </div>
                <div class="table-cell">
                    {{ economic_result }}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

bookingsjef/templates/bookingsjef/generate_price.html
{% extends 'band_booking/base.html' %}
{% block content %}
    <div class="centered">
        <h1 class="generate-scene-header">Genererte billettpriser</h1>
        <div class="generate-scene-boxes">
            {% for i in info %}
            <div class="generate-scene-box">
                <p>Scene: {{ i.name }}</p>
                <p>Billettpris: {{ i.price }}</p>
            </div>
            {% endfor %}
        </div>
    </div>
    <a href="{% url 'bookingsjef:generator_input' %}" class="black-link">
        <div class="generate-scene-button basic-button">
            Tilbake til prisgenerator
        </div>
    </a>
{% endblock %}

bookingsjef/templates/bookingsjef/generator_input.html
{% extends 'band_booking/base.html' %}
{% block content %}
    <form action="{% url 'bookingsjef:price_generator' %}" method="post">
        {% csrf_token %}
        <title>Billettprisgenerator</title>
        <div class="centered">
            <div class="price-generator-input-box">
                <label for markedinfo>Band: </label>
                <input type="text" name="band" class="price-generator-input-field" id="Band" required/>
            </div>
            <div class="price-generator-input-box">
                <label for cost>Honorar: </label>
                <input type="number" name="price" class="price-generator-input-field" id="cost" required/>
            </div>
            <input class="price-generator-button basic-button" value="Generer" type="submit">
        </div>
    </form>
{% endblock %}