IT1901Website/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('bookingansvarlig.urls')),
    url(r'^', include('bookingsjef.urls')),
    url(r'^', include('band_booking.urls')),
    url(r'^', include('tekniker.urls')),
    url(r'^', include('arrangør.urls')),
    url(r'^', include('manager.urls')),
    url(r'^', include('bandmedlem.urls'))
]

band_booking/urls.py
from django.conf.urls import url

from . import views

app_name = 'band_booking'
urlpatterns = [
    url(r'^login(?P<error>(/error))?$', views.login_page, name='login'),
    url(r'^logout$', views.logout, name='logout'),
    url(r'^auth$', views.login_authenticate, name='login_auth'),
    url(r'^artist/(?P<name>([A-Za-z0-9 ]+))$', views.artist_load, name='artist_load'),
    url(r'^get_artist/(?P<name>([A-Za-z0-9 ]+))$', views.artist, name='artist'),
    url(r'^event_information/(?P<name>([A-Za-z0-9 ]+))$', views.event_load, name='past_events'),
    url(r'^index/$', views.index, name='index'),
    url(r'^$', views.index, name='index'),
]

manager/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import permission_required
from . import views

app_name = "manager"

urlpatterns = [
    url(r'^technical_needs/$', views.changeTechnicalneed, name='changeNeeds'),
    url(r'^technical/requirements/$', permission_required('band_booking.see_technical_requirements', login_url="/login")(views.technical_requirements), name='technical_requirements'),
    url(r'^technical/requirements/update/$', permission_required('band_booking.see_technical_requirements', login_url="/login")(views.update_technical_requirements), name='technical_requirements_update'),
]

band_booking/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.utils import timezone


# Create your models here.

class Scene(models.Model):
    """
    Class representing scene.
    """
    number_of_seats = models.IntegerField()
    handicap_accessible = models.NullBooleanField()
    related_name = 'a_scene'
    expenditure = models.IntegerField(default=0)

    # All the choices for the scenes
    STORSALEN = 'Storsalen'
    KLUBBEN = 'Klubben'
    KNAUS = 'Knaus'
    EDGAR = 'Edgar'

    SCENE_CHOICES = (
        (STORSALEN, 'storsalen'),
        (KLUBBEN, 'klubben'),
        (KNAUS, 'knaus'),
        (EDGAR, 'edgar')
    )
    scene_name = models.CharField(
        max_length=16,
        choices=SCENE_CHOICES,
        default=STORSALEN,
    )

    def __str__(self):
        return self.scene_name


class Band(models.Model):
    """
    Class representing band.
    """
    band_name = models.CharField(max_length=30)
    manager = models.OneToOneField(User, limit_choices_to={'groups__name': "Manager"}, null=True, blank=True)
    genre = models.CharField(max_length=20)
    band_member = models.ManyToManyField(User, limit_choices_to={'groups__name': "Bandmedlem"}, related_name='band_member', blank=True)
    booking_price = models.IntegerField(default=0)
    streaming_numbers = models.IntegerField(default=0)

    related_name = "a_band"

    def __str__(self):
        return self.band_name

    def get_band_manager_bookings(self):
        """
        :return: Returns all bookings sent to the manager of the band. Else raises an error.
        Raises:
            ValueError: if band's manager doesn't have an email
        """

        try:
            manager_email = self.manager.email
        except:
            raise ValueError("Manager's email missing")
        return Booking.objects.filter(recipient_email=manager_email)

    @classmethod
    def get_users_band(cls, user: User):
        """
        :param user: The user
        :return: The band the user is a member of if it exists
        """
        try:
            return Band.objects.filter(band_member=user)[:1].get()
        except Band.DoesNotExist:
            return None

    @classmethod
    def equipment(cls, user: User):
        """
        :param user: The user for which we want to find equipment needed
        :return: The equipment needed for the band of the user, if the user is a member of a band.
        """
        user_band = Band.objects.filter(band_member=user)[0]
        return Technical_needs.objects.filter(band=user_band)


class Concert(models.Model):
    """
    Class representation of concert.
    """
    concert_title = models.CharField(max_length=50)
    date = models.DateField()  # got en error with default=date.today() when migrating, so it's been removed
    bands = models.ManyToManyField(Band)  # There can play many bands on the concert and band can play many concerts
    scene = models.ForeignKey(Scene, null=True, blank=True)  # only one scene per concert, but many concerts per scene
    personnel = models.ManyToManyField(User, blank=True)
    attendance = models.IntegerField(default=0)
    ticket_price = models.IntegerField(default=0)
    booking_price = models.IntegerField(default=0)
    organizer = models.ForeignKey(User, limit_choices_to={'groups__name': 'Arrangør'}, null=True, blank=True, related_name='organizer')
    related_name = 'a_concert'

    GUARD_EXPENSE = 1000
    BOOKED = 'B'
    CONTACTED = 'C'
    PAID = 'P'

    STATUS_CHOICES = (
        (BOOKED, 'Booked'),
        (CONTACTED, 'Contacted'),
        (PAID, 'Paid'),
    )

    status = models.CharField(
        max_length=1,
        choices=STATUS_CHOICES,
        default=BOOKED
    )

    def __str__(self):
        return self.concert_title

    def calc_econ_result(self):
        """
        :return: The economic results for the concert
        Calculates the concert's economic result
        """
        return self.ticket_price * self.attendance - self.booking_price - self.scene.expenditure - self.GUARD_EXPENSE

    #
    @property
    def economic_result(self):
        """
        :return: The economic results for the concert
        The economic results for the concert disguised as a field.
        """
        return self.calc_econ_result()


class Technical_needs(models.Model):
    """
    Class representing specific technical needs for the band
    """
    equipment_name = models.CharField(max_length=128, default=' ')
    amount = models.IntegerField(default=1)
    band = models.ForeignKey(Band)

    def __str__(self):
        return self.equipment_name


class Booking(models.Model):
    """
    Class representing band booking.
    """

    EMAIL_MAX_LENGTH = 5000

    sender = models.ForeignKey(User, limit_choices_to={'groups__name': 'Bookingansvarlig'}, null=True, blank=True)
    title_name = models.CharField(max_length=50, default=' ')
    recipient_email = models.EmailField(max_length=50, default=' ')
    email_text = models.CharField(max_length=EMAIL_MAX_LENGTH, default='Booking offer goes here')
    date = models.DateField(default=timezone.now)
    scene = models.ForeignKey(Scene, null=True, blank=True, default=True)

    UNDECIDED = 'U'
    NOT_APPROVED = 'N'
    APPROVED = 'A'
    SENT = 'S'

    STATUS_CHOICES = (
        (UNDECIDED, 'Undecided'),
        (NOT_APPROVED, 'Not approved'),
        (APPROVED, 'Approved'),
        (SENT, 'Sent'),
    )
    status = models.CharField(
        default='U',
        max_length=1,
        choices=STATUS_CHOICES,
    )

    def get_status_message(self):
        """
        Returns a status message in Norwegian for the current status of the booking offer.
        """
        return "Tilbudet er " + self.get_status_word().lower()

    def get_status_word(self):
        """
        Returns a status word in Norwegian for the current status of the booking offer
        """
        status_words = {'U': 'Under godkjenning', 'N': 'Ikke godkjent', 'A': 'Godkjent', 'S': 'Sendt'}
        return status_words[self.status]

    def user_allowed_to_view(self, user):
        """
        Checks if the given user is allowed to view the booking offer
        """
        return self.sender == user or user.has_perm('band_booking.view_all_booking_offers')

    def __str__(self):
        return self.title_name

    def change_status(self, new_status):
        """
        :param new_status: The new status of the booking
        :return: None
        Changes the status of the booking to the new_status
        """
        if new_status in (Booking.UNDECIDED, Booking.NOT_APPROVED, Booking.APPROVED, Booking.SENT):
            self.status = new_status
            self.save()


@receiver(models.signals.post_save, sender=Booking)
def handle_change(sender, **kwargs):
    """
    :param sender: The sender of the Django signal
    :param kwargs: Keyword arguments for the give Django signal
    :return: None
    Sends an email for the given booking that had a change if the stauts was changed to approved.
    """
    booking_object = kwargs['instance']
    if booking_object.status == Booking.APPROVED:
        from bookingansvarlig.actions.send_booking import send_booking
        send_booking(booking_object)
        booking_object.change_status(Booking.SENT)

band_booking/forms.py
from django import forms
from .models import Technical_needs, Band, Concert, User


class ChangeTechnicalneedsForm(forms.ModelForm):
    """
    Form for changing technical needs
    """
    # henter modellen og har nå alle feltene, husk at man må importere den i toppen for å ha tilgang
    class Meta:
        model = Technical_needs
        # må alltid ha en include eller en exclude, den kan være tom
        exclude = ['band']


class CreateBandForm(forms.ModelForm):
    """
    A form for creation of bands
    """
    def __init__(self, *args, **kwargs):
        """
        :param args: Arguments
        :param kwargs: Keyword arguments
        :return: An instance
        Creates an instance with restrictions to the managers that are not already managers for bands
        """
        super(CreateBandForm, self).__init__(*args, **kwargs)
        if self.instance:
            managers = User.objects.all().filter(groups__name='Manager')
            select_able_managers = []
            for manager in managers:
                try:
                    Band.objects.get(manager=manager)
                except Band.DoesNotExist:
                    select_able_managers.append((manager.pk, manager))
            self.fields['manager'].widget.choices = select_able_managers

    class Meta:
        model = Band
        exclude = ['band_member', 'booking_price', 'streaming_numbers']


class CreateConcertForm(forms.ModelForm):
    """
    A form for creation of concerts
    """
    class Meta:
        model = Concert
        exclude = ['personnel', 'attendance', 'organizer', 'status']

band_booking/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout as logout_user
from django.shortcuts import render, redirect, reverse
from datetime import datetime

from band_booking.artist_information_collectors.artist_information import get_artist_information
from band_booking.artist_information_collectors.songkick_collector import get_past_events


def login_page(request, error=None):
    """
    :param request: The HTTP request
    :param error: Any possible error code
    :return: A render of the login view or if the user is already logged in a redirect to the index page.
    """
    if request.user.is_authenticated:
        return redirect('band_booking:index')
    return render(request, 'band_booking/login.html', {'error': error})


def login_authenticate(request):
    """
    :param request: The HTTP request
    :return: A redirect to either the index page or the login page based on if the the login was successful.
    Authenticates the user and login if the username and password are correct, else the user is redirected to the login
    page with an error
    """
    username = request.POST.get('username', None)
    password = request.POST.get('password', None)
    user = authenticate(username=username, password=password)
    if user is not None:
        login(request, user)
        return redirect('band_booking:index')
    else:
        return redirect('login/error')


def logout(request):
    """
    :param request: The HTTP request
    :return: A redirect to the login page
    Logs the user out.
    """
    logout_user(request)
    return redirect('band_booking:login')


def artist(request, name):
    """
    :param request: The HTTP request
    :param name: The name of the artist to search for
    :return: The artist information page for the given artist
    Retrieves artist information and renders page with this information
    """
    return render(request, 'band_booking/artist.html', get_artist_information(name))


def artist_load(request, name):
    """
    :param request: The HTTP request
    :param name: The name of the artist to search for
    :return: A loading page for searching for the given artist
    Renders loading page while artist information is retrieved
    """
    return render(request, 'band_booking/loading_artist.html', {'name': name})


def event_load(request, name):
    """
    :param request: The HTTP request
    :param name: The name of the artist for which to find events
    :return: A page of events for the given artist
    Retrieves past events information for given artist and renders it on the page
    """
    return render(request, 'band_booking/artist_information_events.html', get_past_events(name))


def index(request):
    """
    :param request: The HTTP request
    :return: An index page based on the role of the user containing links to the pages of the given user
    Creates a role specific user index page
    """
    # The pages available to the different roles
    pages = {
        'Bookingansvarlig': [
            {'title': 'Bookingtilbud', 'link': reverse('bookingansvarlig:bookings')},
            {'title': 'Tidligere konserter', 'link': reverse('bookingansvarlig:concerts')},
            {'title': 'Artistinformasjon', 'link': reverse('bookingansvarlig:search_for_artist')},
            {'title': 'Konserter dette semesteret', 'link': reverse('arrangør:concerts')},
        ],
        'Bookingsjef': [
            {'title': 'Tidligere konserter', 'link': reverse('bookingansvarlig:concerts')},
            {'title': 'Bookingtilbud', 'link': reverse('bookingansvarlig:bookings')},
            {'title': 'Billettprisgenerator', 'link': reverse('bookingsjef:generator_input')},
            {'title': 'Bookingoversikt', 'link': reverse('bookingsjef:booking_information_term')}
        ],
        'Arrangør': [
            {'title': 'Konserter dette semesteret', 'link': reverse('arrangør:concerts')},
        ],
        'Tekniker': [
            {'title': 'Mine konserter', 'link': reverse('tekniker:myconcerts')}
        ],
        'Manager': [
            {'title': 'Utstyrsliste', 'link': reverse('manager:technical_requirements')}
        ],
        'Bandmedlem': [
            {'title': 'Konserter', 'link': reverse('bandmedlem:calendar', kwargs={'year': datetime.now().year, 'month': datetime.now().month})},
            {'title': 'Tilbud', 'link': reverse('bandmedlem:bookings')},
        ]
    }

    # If the user is a superuser it should see all the pages
    if request.user.is_superuser:
        super_user_pages = []
        for user_group_pages in pages.values():
            super_user_pages += user_group_pages
        # Removes duplicate links from the admin view
        super_user_pages = list({page['link']: page for page in super_user_pages}.values())
        return render(request, 'band_booking/index.html', {'pages': super_user_pages})

    # Finds the pages for all of the user groups of the user
    user_groups = request.user.groups.all()
    user_pages = []
    for user_group in user_groups:
        if user_group.name in pages:
            user_pages += pages[user_group.name]
    # Remove duplicates caused by users with several groups
    user_pages = list({page['link']: page for page in user_pages}.values())
    return render(request, 'band_booking/index.html', {'pages': user_pages})

band_booking/templates/band_booking/artist.html
{%  if error %}
    <!-- Fix how the error message is displayed -->
    <title>{{ error }}</title>
    <h3>{{ error }}</h3>
{% else %}
    <title>{{ name }}</title>
    <div class="artist-information-wrapper-left">
        <div class="artist-information-band-information">
            <div class="artist-information-band-image-wrapper">
                <img class="artist-information-band-image" src="{{ image.url }}"/>
            </div>
            <div class="artist-information-general-band-information">
                <h2 class="artist-information-band-title" id="band-title">{{ name }}</h2>
                <div class="artist-information-followers">
                    Spotify følgere:
                    <span class="artist-information-followers-number">
                        {{ followers }}
                    </span>
                </div>
                {% if type == "band" %}
                <div class="members">
                    <h4 class="members-title">
                        Medlemmer
                    </h4>
                    <div class="band-members overflow-scroll-x">
                        {% for member in members %}
                            <div class="band-member">{{ member }}</div>
                        {% endfor %}
                    </div>
                </div>
                {% endif %}
            </div>
        </div>

        <div class="events">
            <h3 class="events-title">Konserter</h3>
            <div id="events-list">
                <div class="concert-load"> Laster konsert information<span id="loading_information_animation_dots"></span></div>
            </div>
        </div>
    </div>

    <div class="albums overflow-scroll-x">
        <h3 class="albums-title">
            Albums
        </h3>
        {% for album in albums %}
            <div class="album">
                <img class="album-image" src="{{ album.image.url }}"/>
                <div class="album-information">
                    <span class="album-title">
                    {{ album.name }} -
                        <span class="album-popularity">
                            Popularitet: {{ album.popularity }}/100
                        </span>
                        <span class="album-information-title-divider">
                            -
                        </span>
                        <span class="album-sales">
                            Salg: {{ album.sales }}
                        </span>
                    </span>
                    <div class="album-tracks">
                        <div class="tracks table">
                            {% for track in album.tracks %}
                                <div class="track table-row">
                                    <span class="track-number table-cell">
                                        {{ track.track_number }}
                                    </span>
                                    <span class="track-name table-cell">
                                        {{ track.name }}
                                    </span>
                                    <span class="track-time table-cell">
                                        {{ track.duration }}
                                    </span>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endif %}

band_booking/templates/band_booking/artist_information_events.html
{% if error %}
    <div class="artist-information-event-error">
        {{ error }}
    </div>
{% else %}
    <div class="artist-information-events-table">
        <div class="artist-information-event-table-wrapper-table">
            <div class="artist-information-event-headers">
                <span class="table-cell small-padding-right">
                    Konsert navn
                </span>
                <span class="artist-information-event-date-header table-cell small-padding-right small-padding-left">
                    Dato
                </span>
                <span class="artist-information-event-city-header table-cell small-padding-left">
                    Sted
                </span>
            </div>
        </div>
        <div class="artist-information-event-table-wrapper overflow-scroll-y">
            <div class="artist-information-event-table-wrapper-table">
                <div class="artist-information-event-table-events overflow-scroll-y table-row-group">
                    {% for event in events %}
                        <div class="artist-information-event">
                            <span class="table-cell small-padding-right">
                                {{ event.name }}
                            </span>
                            <span class="artist-information-event-date table-cell small-padding-right small-padding-left">
                                {{ event.date }}
                            </span>
                            <span class="artist-information-event-city table-cell small-padding-left">
                                {{ event.city }}
                            </span>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{%  endif %}

band_booking/templates/band_booking/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'band_booking/style/style.css' %}">
</head>
<body>
<header>
    <div class="navbar">
        <div class="logo inline-block">
            <a href="{% url 'band_booking:index' %}">
                <img src="{% static 'band_booking/images/logo.png' %}" class="logo-image">
            </a>
        </div>
        <div class="user-info inline">
            {% if user.is_superuser %}
                <span class="username">
                    <a href="/admin" class="white-link bold">Admin</a>
                </span>
                <span class="user-info-divider">
                    ||||
                </span>
            {% endif %}
            <span class="username">
                {% if user.first_name %}
                    {{ user.first_name }} {{ user.last_name }}
                {% else %}
                    {{ user.username }}
                {% endif %}
            </span>
            <span class="user-info-divider">
                ||||
            </span>
            <span class="logout-button">
                <a href="{% url 'band_booking:logout' %}">Logg ut</a>
            </span>
        </div>
    </div>
</header>
<main>
    <div class="content" id="content">
        {% block content %}
        {% endblock %}
    </div>
</main>
</body>
</html>

band_booking/templates/band_booking/error.html
{% extends 'band_booking/base.html' %}
{% load static %}
{% block content %}
	<title>Error</title>
	<div>
		<h3 class="center-horizontal"> {{ error }} </h3>
	</div>
{% endblock %}

band_booking/templates/band_booking/index.html
{% extends 'band_booking/base.html' %}
{% block content %}
    <title>Meny</title>
    <div class="menu-links centered">
        {% for page in pages %}
            <a href="{{ page.link }}" class="black-link">
                <div class="menu-link basic-button">
                <span class="menu-link-title">
                    {{ page.title }}
                </span>
                </div>
            </a>
        {% endfor %}
    </div>
{% endblock %}

band_booking/templates/band_booking/loading_artist.html
{% extends 'band_booking/base.html' %}
{% load static %}
{% block content %}
    <title>{{ name }}</title>

    <div class="artist-information-loading-wrapper centered" id="loading_information">
        <div class="loading_information_text">
            Laster informasjon om
        <span class="artist-information-loading-artist-name">
            {{ name }}
        </span>
        </div>
        <div class="artist-information-loading-description">
            Kan ta opptil 5 sekunder
        </div>
        <div class="artist-information-loading-animation" id="loading_information_animation_dots"></div>
    </div>

    <div class="hidden" id="artist">{{ name }}</div>
    <script src="{% static 'band_booking/scripts/loading_artist.js' %}"></script>
{% endblock content %}

band_booking/templates/band_booking/login.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'band_booking/style/style.css' %}"/>

<div class="centered login-area">
    {% if error %}
        <div class="login-error" id="login_error">
            <div class="login-error-message">
                Feil brukernavn eller passord
            </div>
            <span class="dismiss">
                <input id="dismiss_message_button" type="button" class="hover-pointer login-dismiss-message-button"/>
            </span>
        </div>
    {% endif %}
    <form action="{% url 'band_booking:login_auth' %}" method="post">
        {% csrf_token %}
        <div class="login-field">
            <label for="username">Brukernavn: </label>
            <input type="text" name="username" class="login-input-field" id="username"/>
        </div>
        <div class="login-field">
            <label for="password">Passord: </label>
            <input type="password" name="password" class="login-input-field" id="password">
        </div>
        <input class="login-button basic-button" value="Logg inn" type="submit">
    </form>
</div>

<script src="{% static 'band_booking/scripts/login.js'%}"></script>